name: "Trivy"

on:
  workflow_dispatch:
  # Trigger manually
  workflow_run:
    workflows: [Publish docker image]
    types: [completed]

jobs:
  prepare-env:
    runs-on: ubuntu-latest
    outputs:
      check_sha: ${{ steps.step1.outputs.check_sha }}
    steps:
      - name: Set commit SHA to check
        id: step1
        run: |
          if [ -z "${{ github.event.workflow_run.head_sha }}" ]; then
            # use the value that is set when triggering the workflow manually
            echo "::set-output name=check_sha::$GITHUB_SHA"
          else
            echo "::set-output name=check_sha::${{ github.event.workflow_run.head_sha }}"
          fi

  analyze-config:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    needs: [prepare-env]
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{needs.prepare-env.outputs.check_sha}}

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "config"
          exit-code: "1"
          hide-progress: false
          format: "sarif"
          output: "trivy-results1.sarif"
          severity: "CRITICAL,HIGH"
          timeout: "10m0s"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: "trivy-results1.sarif"

  analyze-traceability-foss-backend:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    needs: [prepare-env]
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{needs.prepare-env.outputs.check_sha}}

      - name: Run Trivy vulnerability scanner
        if: always()
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/eclipse-tractusx/traceability-foss-backend:${{needs.prepare-env.outputs.check_sha}}
          trivyignores: "./.github/workflows/.trivyignore"
          format: "sarif"
          output: "trivy-results2.sarif"
          severity: "CRITICAL,HIGH"
          timeout: "10m0s"

      - name: Upload Trivy scan results to GitHub Security tab
        if: always()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: "trivy-results2.sarif"
